image: atlassian/default-image:3

pipelines:
  default:
    - parallel:
        - step:
            name: "Build and Test"
            script:
              - echo "Your build and test goes here..."
        - step:
            name: "Lint"
            script:
              - echo "Your linting goes here..."
        - step:
            name: "Security scan"
            script:
              - echo "Your security scan goes here..."

  branches:
    "*":
      - step:
          name: Sync GitHub Mirror
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - git clone --bare git@bitbucket.org:sithiktn/clone_java_app.git
            - cd clone_java_app.git
            - git push --mirror git@github.com:abu-sithik/test_clone_java.git
      # Deployment steps will be executed for each pipeline run
      # To configure your steps and conditionally deploy see https://support.atlassian.com/bitbucket-cloud/docs/configure-bitbucket-pipelinesyml/
      - step:
          name: "Deployment to Staging"
          deployment: staging
          script:
            - echo "Your deployment to staging script goes here..."
      - step:
          name: "Deployment to Production"
          deployment: production
          trigger: "manual"
          script:
            - echo "Your deployment to production script goes here..."